version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=True
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    #esperará a que db se ejecute antes de activarse.
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      #se enlaza con el nombre del servicio de volumes y : la ubiacion viene descrita en doc oficial de la imagen postgre en docker y dockerhub 
      - dev-db-data:/var/lib/postgresql/data
    environment:
    # al crear la db, es solo para local
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
volumes:
  dev-db-data:
  dev-static-data:
